# fly.toml app configuration file generated for uaas on 2024-08-03T10:27:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uaas'
primary_region = 'ewr'

[build]

[env]
  PORT = '8080'

[mounts]
  source = 'counts_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
